<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GPRRRCM" failures="0" tests="6" name="testcases.ProductDataDrivenTest" time="0.539" errors="1" timestamp="2025-09-03T02:06:05 IST" skipped="5">
  <testcase classname="testcases.ProductDataDrivenTest" name="testAddNewProduct" time="0.000">
    <skipped/>
  </testcase> <!-- testAddNewProduct -->
  <testcase classname="testcases.ProductDataDrivenTest" name="testAddNewProduct" time="0.004">
    <skipped/>
  </testcase> <!-- testAddNewProduct -->
  <testcase classname="testcases.ProductDataDrivenTest" name="testAddNewProduct" time="0.000">
    <skipped/>
  </testcase> <!-- testAddNewProduct -->
  <testcase classname="testcases.ProductDataDrivenTest" name="testAddNewProduct" time="0.000">
    <skipped/>
  </testcase> <!-- testAddNewProduct -->
  <testcase classname="testcases.ProductDataDrivenTest" name="testAddNewProduct" time="0.000">
    <skipped/>
  </testcase> <!-- testAddNewProduct -->
  <testcase classname="testcases.ProductDataDrivenTest" name="setup" time="0.535">
    <error message=".\logs\test_logging.log (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: .\logs\test_logging.log (The system cannot find the path specified)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:255)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:210)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:120)
at testcases.BaseClass.setup(BaseClass.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- setup -->
</testsuite> <!-- testcases.ProductDataDrivenTest -->
